In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

In [3]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1.shape

(2, 3)

In [5]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
print(arr.ravel())
arr.ravel('F')

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [7]:
np.arange(2).reshape(2,1)

array([[0],
       [1]])