# Advanced NumPy

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## ndarray Object Internals

In [2]:
np.ones((10, 5)).shape

(10, 5)

In [3]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

### NumPy dtype Hierarchy

In [4]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)

True

In [5]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [6]:
np.issubdtype(ints.dtype, np.number)

True

## Advanced Array Manipulation

### Reshaping Arrays

In [7]:
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [8]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [10]:
other_arr = np.ones((3, 5))
print("-----------other_arr---------")
print(other_arr)
print(other_arr.shape)
print("-------arr---------")
print(arr)
arr.reshape(other_arr.shape)

-----------other_arr---------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 5)
-------arr---------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [11]:
arr = np.arange(15).reshape((5, 3))
print(arr)
print("---------------")
arr.ravel() #back to be flatten by ravel(), same as flatten()

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
---------------


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### C Versus Fortran Order

In [13]:
arr = np.arange(12).reshape((3, 4))
arr
print(arr.ravel())
arr.ravel('F')

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

### Concatenating and Splitting Arrays

In [39]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  #(2,6)
print(arr1)
print("---------")
arr2 = np.array([[7, 8, 9], [10, 11, 12]]) #(2,6)
print(arr2)
print("===========================")

print("concatenate axis=0 : ")
print(np.concatenate([arr1, arr2], axis=0)) #
print("concatenate axis=1 : ")
print(np.concatenate([arr1, arr2], axis=1))

print("concatenate axis=1 : ")
print(np.concatenate([arr1, np.arange(2).reshape(2,1)], axis=1))

[[1 2 3]
 [4 5 6]]
---------
[[ 7  8  9]
 [10 11 12]]
concatenate axis=0 : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
concatenate axis=1 : 
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [40]:
print(np.vstack((arr1, arr2)))  #np.concatenate axis=0
print("-------------------------")
print(np.hstack((arr1, arr2)))  #np.concatenate axis=1

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
-------------------------
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[split , on the other hand, slices apart an array into multiple arrays along an axis:](https://www.tutorialsandyou.com/python/numpy-split-in-python-76.html)
* The code np.split(x, 2) has splitted Numpy array x into two equal sub-arrays- [1, 2] and [3, 4]
* The code np.split(y, [2, 3]) has splitted array y into three sub-arrays- y[:2], y[2:3] and y[3:]

In [62]:
print ('Split the array at positions indicated in 1-D array:' )
arr = np.random.randn(5, 2)
print(arr)

print("==========================")
first, second, third = np.split(arr, [5, 3]) #
print("-----first----------")
print(first)
print("-----second----------")
print(second)
print("-----third----------")
print(third)

print("==========================")
first, second, third = np.split(arr, [2, 3]) #
print("-----first----------")
print(first)
print("-----second----------")
print(second)
print("-----third----------")
print(third)
print("==========================")
first, second, third = np.split(arr, [1, 2]) #
print("-----first----------")
print(first)
print("-----second----------")
print(second)
print("-----third----------")
print(third)


Split the array at positions indicated in 1-D array:
[[-0.4457  0.4684]
 [-0.9616 -1.8245]
 [ 0.6254  1.0229]
 [ 1.1074  0.0909]
 [-0.3501  0.218 ]]
-----first----------
[[-0.4457  0.4684]
 [-0.9616 -1.8245]
 [ 0.6254  1.0229]
 [ 1.1074  0.0909]
 [-0.3501  0.218 ]]
-----second----------
[]
-----third----------
[[ 1.1074  0.0909]
 [-0.3501  0.218 ]]
-----first----------
[[-0.4457  0.4684]
 [-0.9616 -1.8245]]
-----second----------
[[0.6254 1.0229]]
-----third----------
[[ 1.1074  0.0909]
 [-0.3501  0.218 ]]
-----first----------
[[-0.4457  0.4684]]
-----second----------
[[-0.9616 -1.8245]]
-----third----------
[[ 0.6254  1.0229]
 [ 1.1074  0.0909]
 [-0.3501  0.218 ]]


In [63]:
#numpy.split(ary, indices_or_sections, axis)

#indices_or_sections : 
# Can be an integer, indicating the number of equal sized subarrays 
# to be created from the input array. If this parameter is a 1-D array, 
# the entries indicate the points at which a new subarray is to be created.

# axis : default is 0 (row , below direction)
import numpy as np 
a = np.arange(9) 

print ('First array:')
print (a )


print ('Split the array in 3 equal-sized subarrays:' )
b = np.split(a,3) 
print( b )
 

print ('Split the array at positions indicated in 1-D array:' )
b = np.split(a,[4,7])
print (b) 

First array:
[0 1 2 3 4 5 6 7 8]
Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


#### Stacking helpers: r_ and c_

In [108]:
arr = np.arange(6)

arr1 = arr.reshape((3, 2))
print(arr1)
print("--------------")
arr2 = np.random.randn(3, 2)
print(arr2)
print("------=======np.r_--------")
print("--np.r_[arr1, arr2]")
print(np.r_[arr1, arr2])  #.r_  row base concatenate axis=0
print("--concatenate((a,b)), axis = 0)")
print(np.concatenate((arr1, arr2), axis=0))
print("--concatenate([a,b], axis = 0)")
print(np.concatenate([arr1, arr2], axis=0))
print("--------=======np.c_-----------")
print(np.c_[np.r_[arr1, arr2], arr])  #.c_ column base concatenate axis=1
print("---- ---- ---")
# print("--np.concatenate( [np.concatenate([arr1, arr2], axis=0), arr], axis=1 ) ") #error 2d vs 1d
# print(np.concatenate( [np.concatenate([arr1, arr2], axis=0), arr], axis=1 ) )
#TypeError: concatenate() got multiple values for argument 'axis'
# print(np.concatenate( np.concatenate([arr1, arr2], axis=0), arr, axis=1 ) ) S
temp1 = np.concatenate([arr1, arr2], axis=0)
print(temp1.shape)
print(temp1)
print('********')
print(arr.shape)
print(arr)
print("-------")
# ValueError: all the input arrays must have same number of dimensions,
# but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
print(np.concatenate( [temp1, arr.reshape(6,1)], axis=1 ) ) 
print("-------")
# np.hstack((temp1,arr)) #error 2d vs. 1d
np.hstack((temp1,arr.reshape(6,1)))

[[0 1]
 [2 3]
 [4 5]]
--------------
[[-0.2551  0.8541]
 [-0.3648  0.1311]
 [-0.6976  1.3356]]
------=======np.r_--------
--np.r_[arr1, arr2]
[[ 0.      1.    ]
 [ 2.      3.    ]
 [ 4.      5.    ]
 [-0.2551  0.8541]
 [-0.3648  0.1311]
 [-0.6976  1.3356]]
--concatenate((a,b)), axis = 0)
[[ 0.      1.    ]
 [ 2.      3.    ]
 [ 4.      5.    ]
 [-0.2551  0.8541]
 [-0.3648  0.1311]
 [-0.6976  1.3356]]
--concatenate([a,b], axis = 0)
[[ 0.      1.    ]
 [ 2.      3.    ]
 [ 4.      5.    ]
 [-0.2551  0.8541]
 [-0.3648  0.1311]
 [-0.6976  1.3356]]
--------=======np.c_-----------
[[ 0.      1.      0.    ]
 [ 2.      3.      1.    ]
 [ 4.      5.      2.    ]
 [-0.2551  0.8541  3.    ]
 [-0.3648  0.1311  4.    ]
 [-0.6976  1.3356  5.    ]]
---- ---- ---
(6, 2)
[[ 0.      1.    ]
 [ 2.      3.    ]
 [ 4.      5.    ]
 [-0.2551  0.8541]
 [-0.3648  0.1311]
 [-0.6976  1.3356]]
********
(6,)
[0 1 2 3 4 5]
-------
[[ 0.      1.      0.    ]
 [ 2.      3.      1.    ]
 [ 4.      5.      2.    ]
 [

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [-0.2551,  0.8541,  3.    ],
       [-0.3648,  0.1311,  4.    ],
       [-0.6976,  1.3356,  5.    ]])

In [109]:
a = np.arange(1,6)
print(a)
b= np.arange(-10, -5)
print(b)
print("------np.r_[a,b]-------")
print(np.r_[a,b])
np.c_[a, b]

[1 2 3 4 5]
[-10  -9  -8  -7  -6]
------np.r_[a,b]-------
[  1   2   3   4   5 -10  -9  -8  -7  -6]


array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [110]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

### Repeating Elements: tile and repeat

In [112]:
arr = np.arange(3)
print(arr)
arr.repeat(3)

[0 1 2]


array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [20]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [114]:
arr = np.random.randn(2, 2)
print(arr)
print("--------------")
arr.repeat(2, axis=0)

[[ 0.3563 -0.0101]
 [ 1.4158  0.5661]]
--------------


array([[ 0.3563, -0.0101],
       [ 0.3563, -0.0101],
       [ 1.4158,  0.5661],
       [ 1.4158,  0.5661]])

In [115]:
print(arr.repeat([2, 3], axis=0))  #first row 2 times, second row 3 times
arr.repeat([2, 3], axis=1) #1sst column 2times, 2nd column 3times

[[ 0.3563 -0.0101]
 [ 0.3563 -0.0101]
 [ 1.4158  0.5661]
 [ 1.4158  0.5661]
 [ 1.4158  0.5661]]


array([[ 0.3563,  0.3563, -0.0101, -0.0101, -0.0101],
       [ 1.4158,  1.4158,  0.5661,  0.5661,  0.5661]])

In [118]:
arr
print(np.tile(arr, 2)) #whoel arr repeat column wise 2 times
print("---------------")
print(arr.repeat(2, axis=1)) # each colum repeat colum wise 2 times

[[ 0.3563 -0.0101  0.3563 -0.0101]
 [ 1.4158  0.5661  1.4158  0.5661]]
---------------
[[ 0.3563  0.3563 -0.0101 -0.0101]
 [ 1.4158  1.4158  0.5661  0.5661]]


In [119]:
arr
print(np.tile(arr, (2, 1)))
print("------------------------------")
np.tile(arr, (3, 2))#whole arr repeat row wise 3times , whole arr repeat column wise 2 times

[[ 0.3563 -0.0101]
 [ 1.4158  0.5661]
 [ 0.3563 -0.0101]
 [ 1.4158  0.5661]]
------------------------------


array([[ 0.3563, -0.0101,  0.3563, -0.0101],
       [ 1.4158,  0.5661,  1.4158,  0.5661],
       [ 0.3563, -0.0101,  0.3563, -0.0101],
       [ 1.4158,  0.5661,  1.4158,  0.5661],
       [ 0.3563, -0.0101,  0.3563, -0.0101],
       [ 1.4158,  0.5661,  1.4158,  0.5661]])

### Fancy Indexing Equivalents: take and put

In [146]:
arr = np.arange(10) * 100
print(arr)
print("--------------------")
inds = [7, 1, 2, 6]  #reorder arr according to [index 7th element, 1st, 2nd...]
arr[inds]

[  0 100 200 300 400 500 600 700 800 900]
--------------------


array([700, 100, 200, 600])

In [147]:
############ ? #############
# put: Replaces specified elements of an array with given values.
print(arr)
print("--")
print(arr.take(inds))
print(arr[inds])
print(inds)
print("---------------")
arr.put(inds, 42) #replace all inds' element values with 42
print("*replace inds 7's value 700 to 42, 1's 100 to 42, 2's 200 to 42...from arr ")
print(arr)
arr.put(inds, [40, 41, 42, 43])
arr

[  0 100 200 300 400 500 600 700 800 900]
--
[700 100 200 600]
[700 100 200 600]
[7, 1, 2, 6]
---------------
*replace inds 7's value 700 to 42, 1's 100 to 42, 2's 200 to 42...from arr 
[  0  42  42 300 400 500  42  42 800 900]


array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [150]:
inds = [2, 0, 2, 1]
arr = np.random.randn(2, 4)
print(arr)
arr.take(inds, axis=1) #column-wise reorder element of index 2-> first, index 0-> second...

[[-0.0316  0.2341  0.2719  1.2308]
 [ 1.2883  0.8518 -1.5292 -1.5517]]


array([[ 0.2719, -0.0316,  0.2719,  0.2341],
       [-1.5292,  1.2883, -1.5292,  0.8518]])

## Broadcasting

In [151]:
arr = np.arange(5)
arr
arr * 4

array([ 0,  4,  8, 12, 16])

In [177]:
arr = np.random.randn(4, 3)
print(arr)
print("----arr.mean(0): row-wise(top-to-bottom): ttl 3----")
print(arr.mean(0))
print("-------arr-arr.mean(0)-------------")
demeaned = arr - arr.mean(0)
print(demeaned)
print("----------------------------")
print(demeaned.mean(0))

print("============")
sum(arr -arr.mean(0)) / len(arr[:,0])

[[-0.7164 -0.1033 -1.141 ]
 [-0.5008 -0.3893 -0.4739]
 [ 0.1287  0.1537  0.4448]
 [ 0.1285  0.2525 -0.9406]]
----arr.mean(0): row-wise(top-to-bottom): ttl 3----
[-0.24   -0.0216 -0.5277]
-------arr-arr.mean(0)-------------
[[-0.4764 -0.0817 -0.6134]
 [-0.2608 -0.3677  0.0538]
 [ 0.3687  0.1753  0.9725]
 [ 0.3685  0.2741 -0.413 ]]
----------------------------
[ 0.  0. -0.]


array([ 0.,  0., -0.])

In [168]:
print(round(sum(arr[:,0])/len(arr[:,0]), 4))
sum(arr)/len(arr[:,0])

-0.0805


array([-0.0805,  1.0339, -0.1469])

In [169]:
arr[:,0].sum()/len(arr[:,0])

-0.08049476799496183

In [181]:
print(arr)
print("----columnwise (left to right) mean: ttl 4-----------")
row_means = arr.mean(1) #columnwise (left to right)
print(" --1st col mean, 2nd , 3rd, 4th")
print(row_means)
print(row_means.shape)
print(row_means.reshape((4, 1)))
print("-----------------")
demeaned = arr - row_means.reshape((4, 1))
print(demeaned.mean(1))
demeaned.mean(1).reshape(4,1)

[[-0.7164 -0.1033 -1.141 ]
 [-0.5008 -0.3893 -0.4739]
 [ 0.1287  0.1537  0.4448]
 [ 0.1285  0.2525 -0.9406]]
----columnwise (left to right) mean: ttl 4-----------
 --1st col mean, 2nd , 3rd, 4th
[-0.6536 -0.4546  0.2424 -0.1865]
(4,)
[[-0.6536]
 [-0.4546]
 [ 0.2424]
 [-0.1865]]
-----------------
[-0. -0.  0.  0.]


array([[-0.],
       [-0.],
       [ 0.],
       [ 0.]])

### Broadcasting Over Other Axes

In [184]:
print(arr.shape)
print(arr.mean(1).shape)

(4, 3)
(4,)


In [182]:
arr - arr.mean(1)#ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [185]:
arr - arr.mean(1).reshape((4, 1))

array([[-0.0628,  0.5503, -0.4875],
       [-0.0461,  0.0653, -0.0192],
       [-0.1137, -0.0887,  0.2024],
       [ 0.3151,  0.4391, -0.7541]])

In [188]:
sum(arr - arr.mean(1).reshape((4, 1))).reshape(4,1)

array([[0.],
       [0.],
       [0.],
       [0.]])

In [186]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape
arr_1d = np.random.normal(size=3)
arr_1d[:, np.newaxis]
arr_1d[np.newaxis, :]

array([[ 1.0021, -0.5254, -0.8874]])

In [214]:
arr = np.random.randn(3, 4, 5)
print(arr)
print("--------------")
depth_means = arr.mean(2)
print(depth_means)
print(depth_means.shape)
print("-----====--------")
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

[[[-1.5556  1.103   0.5547 -1.289   0.3852]
  [-1.7173 -1.0184  0.0516  0.5033 -0.5432]
  [-0.5067  0.7297  0.4343 -1.1337  1.424 ]
  [ 0.2664 -0.8543 -0.5506 -0.6191  1.0389]]

 [[-0.9106  0.53   -0.0085 -1.129   0.5699]
  [-0.8634 -1.3561 -0.0572 -0.1086  1.6524]
  [-1.3509 -0.5461  0.9914  2.201   0.4279]
  [ 0.2905  0.612  -0.5125 -0.7242  1.6929]]

 [[-0.2993  1.5717  0.4614 -0.6738 -1.141 ]
  [-1.2289 -1.1593 -0.3208  1.0883 -0.9062]
  [-0.4642 -0.5134  1.6178 -0.8167  0.2447]
  [-1.3111  0.3884  1.5924  0.8704  0.3352]]]
--------------
[[-0.1603 -0.5448  0.1895 -0.1437]
 [-0.1897 -0.1466  0.3447  0.2717]
 [-0.0162 -0.5054  0.0137  0.3751]]
(3, 4)
-----====--------


array([[-0., -0.,  0., -0.],
       [ 0., -0., -0.,  0.],
       [ 0., -0., -0.,  0.]])

In [215]:
arr = np.random.randn(3, 4, 5) #row:3, column:4 , depth:5
print(arr)
print("------arr.mean(2) -> depth:5's mean --------")
depth_means = arr.mean(2)
print(depth_means)
print(depth_means.shape)
print("-----====--------")
print(arr.shape)
print(depth_means.shape)
demeaned = arr - depth_means[:, :, np.newaxis] # convert 2d to 3d by [:,:,np.newaxis]
demeaned.mean(2)

[[[ 0.649  -0.1832  0.5002  1.3688  0.8951]
  [ 0.6473 -0.5679 -0.5795 -0.7514  1.0755]
  [-0.6211  1.8786  1.2602  0.3101  0.1064]
  [ 0.248  -1.3938 -0.6694 -0.5668 -0.3818]]

 [[-0.9465 -1.0651 -1.3318 -0.9865 -0.3784]
  [ 0.7647  0.0604  0.6185 -0.4849 -0.2805]
  [ 0.407   1.0252  0.2548  0.0875  0.0707]
  [-0.5732  1.2289 -0.9622  1.5256  0.8273]]

 [[ 0.9125 -0.1273  0.6343 -1.5309 -1.2907]
  [-0.5262 -1.1322 -0.4998 -0.7285 -0.5831]
  [ 0.3293 -0.8269 -0.5369 -0.563   0.9184]
  [-0.0794 -0.2786 -0.1305 -1.397  -0.2447]]]
------arr.mean(2) -> depth:5's mean --------
[[ 0.646  -0.0352  0.5868 -0.5528]
 [-0.9417  0.1356  0.369   0.4093]
 [-0.2804 -0.694  -0.1358 -0.426 ]]
(3, 4)
-----====--------
(3, 4, 5)
(3, 4)


array([[-0.,  0.,  0., -0.],
       [-0., -0., -0., -0.],
       [ 0., -0.,  0.,  0.]])

```python
def demean_axis(arr, axis=0):
    means = arr.mean(axis)

    # This generalizes things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]
```

### Setting Array Values by Broadcasting

In [216]:
#setting values via array indexing.
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [217]:
arr = np.zeros((4, 3))
arr[:,:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [218]:
## Set into column: row number must be matched, rows are replaced.

# if we had a one-dimensional array of values we wanted 
# to set into the columns of the array, 
# we can do that as long as the shape is compatible:
col = np.array([1.28, -0.42, 0.44, 1.6])
print("** col, ", col.shape); print(col)
print("*** arr, ",arr.shape); print(arr)
print("----------------------------------")
print("* col[:,np.newaxis].shape :",col[:,np.newaxis].shape)
print(col[:,np.newaxis])
print("-----arr[:] = col[:, np.newaxis]----------")
arr[:] = col[:, np.newaxis] #set into the column of array:for all columns, all rows are replaced
print(arr)
arr[:2] = [[-1.37], [0.509]] #for all columns, row1 and row 2 are replaced with-1.37 and 0.509 
arr

** col,  (4,)
[ 1.28 -0.42  0.44  1.6 ]
*** arr,  (4, 3)
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
----------------------------------
* col[:,np.newaxis].shape : (4, 1)
[[ 1.28]
 [-0.42]
 [ 0.44]
 [ 1.6 ]]
-----arr[:] = col[:, np.newaxis]----------
[[ 1.28  1.28  1.28]
 [-0.42 -0.42 -0.42]
 [ 0.44  0.44  0.44]
 [ 1.6   1.6   1.6 ]]


array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [220]:
## columns number must be matched: columns are replaced
# arr = np.arange(12).reshape(3,4)
arr = np.random.randn(3, 4)
row = np.array([1.28, -0.42, 0.44, 1.6])
print("** row, ", row.shape); print(row)
print("*** arr, ",arr.shape); print(arr)
print("----------------------------------")
print("* row[np.newaxis,:].shape :",row[np.newaxis,:].shape)
print(row[np.newaxis,:])
print("-----arr[:] = row[np.newaxis, :]----------")
arr[:] = row[np.newaxis,:] #set into the row of array:for all rows, all columns are replaced
print(arr)
arr[:2] = [[-1.37], [0.509]] #for all row, col 1 and col 2 are replaced with-1.37 and 0.509 
arr

** row,  (4,)
[ 1.28 -0.42  0.44  1.6 ]
*** arr,  (3, 4)
[[ 0.8303  0.2408 -0.9157 -2.2253]
 [-0.6631 -0.3212  0.4984  0.3803]
 [-1.067   0.2555  2.1113 -0.6342]]
----------------------------------
* row[np.newaxis,:].shape : (1, 4)
[[ 1.28 -0.42  0.44  1.6 ]]
-----arr[:] = row[np.newaxis, :]----------
[[ 1.28 -0.42  0.44  1.6 ]
 [ 1.28 -0.42  0.44  1.6 ]
 [ 1.28 -0.42  0.44  1.6 ]]


array([[-1.37 , -1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509,  0.509],
       [ 1.28 , -0.42 ,  0.44 ,  1.6  ]])

## Advanced ufunc Usage

### ufunc Instance Methods

In [222]:
# reduce takes a single array and aggregates its values, optionally along an axis,
arr = np.arange(10)
print(np.add.reduce(arr))
arr.sum()

45


45

In [246]:
np.random.seed(12346)  # for reproducibility
arr = np.random.randn(5, 5)
print(arr)
print("------ arr[::2]----") #from start, to end, increment 2
print(arr[::2])
print("------ arr[::1]----") #increment 1
print(arr[::1])
print("------ arr[::3]----") #increment 3
print(arr[::3])

print("arr---")
print(arr)
print("************")
print(arr[::2])

print("-----after arr[::2].sort(1)-for every other row(increment 2)-(default is row),column wise(left to right) sort----")
arr[::2].sort(1) # sort only even row, sorting method: column-wise(left to right) sort.
print(arr)
print("======arr[:, :-1]========")
print(arr[:, :-1])
print("---- arr[:, 1:]------")
print( arr[:, 1:])
print("---------arr[:, :-1] < arr[:, 1:]------")
print(arr[:, :-1] < arr[:, 1:])

np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1) #column-wise, from left to right 'np.logical_and' op

[[-0.09    0.7594  0.7483 -0.9815  0.3658]
 [-0.3154 -0.8661  0.0279 -0.4556 -1.6019]
 [ 0.2483 -0.3215 -0.8487  0.0005 -0.5465]
 [ 0.2539  1.9368 -0.7995 -0.5692  0.0489]
 [-0.6491 -0.4795 -0.9535  1.4225  0.1754]]
------ arr[::2]----
[[-0.09    0.7594  0.7483 -0.9815  0.3658]
 [ 0.2483 -0.3215 -0.8487  0.0005 -0.5465]
 [-0.6491 -0.4795 -0.9535  1.4225  0.1754]]
------ arr[::1]----
[[-0.09    0.7594  0.7483 -0.9815  0.3658]
 [-0.3154 -0.8661  0.0279 -0.4556 -1.6019]
 [ 0.2483 -0.3215 -0.8487  0.0005 -0.5465]
 [ 0.2539  1.9368 -0.7995 -0.5692  0.0489]
 [-0.6491 -0.4795 -0.9535  1.4225  0.1754]]
------ arr[::3]----
[[-0.09    0.7594  0.7483 -0.9815  0.3658]
 [ 0.2539  1.9368 -0.7995 -0.5692  0.0489]]
arr---
[[-0.09    0.7594  0.7483 -0.9815  0.3658]
 [-0.3154 -0.8661  0.0279 -0.4556 -1.6019]
 [ 0.2483 -0.3215 -0.8487  0.0005 -0.5465]
 [ 0.2539  1.9368 -0.7995 -0.5692  0.0489]
 [-0.6491 -0.4795 -0.9535  1.4225  0.1754]]
************
[[-0.09    0.7594  0.7483 -0.9815  0.3658]
 [ 0.2483 -0

array([ True, False,  True, False,  True])

In [245]:
print(arr)
print("======arr[:, :-2]========") #all row, colunm is from start to (-2: from rear 2nd -> this is not incl)
print(arr[:, :-2])
print("======arr[::-2]========")# increment -2 row-wise(default)-every other row (from rear)
print(arr[::-2])
print("---- arr[:, 2:]------") #all row, column is from 2 row to the end.
print( arr[:, 2:])

[[-0.9815 -0.09    0.3658  0.7483  0.7594]
 [-0.3154 -0.8661  0.0279 -0.4556 -1.6019]
 [-0.8487 -0.5465 -0.3215  0.0005  0.2483]
 [ 0.2539  1.9368 -0.7995 -0.5692  0.0489]
 [-0.9535 -0.6491 -0.4795  0.1754  1.4225]]
======arr[:, :-2]========
[[-0.9815 -0.09    0.3658]
 [-0.3154 -0.8661  0.0279]
 [-0.8487 -0.5465 -0.3215]
 [ 0.2539  1.9368 -0.7995]
 [-0.9535 -0.6491 -0.4795]]
======arr[::-2]========
[[-0.9535 -0.6491 -0.4795  0.1754  1.4225]
 [-0.8487 -0.5465 -0.3215  0.0005  0.2483]
 [-0.9815 -0.09    0.3658  0.7483  0.7594]]
---- arr[:, 2:]------
[[ 0.3658  0.7483  0.7594]
 [ 0.0279 -0.4556 -1.6019]
 [-0.3215  0.0005  0.2483]
 [-0.7995 -0.5692  0.0489]
 [-0.4795  0.1754  1.4225]]


In [248]:
#It produces an array of the same size 
# with the intermediate “accumulated” values:
arr = np.arange(15).reshape((3, 5))
print(arr)
print("-----------------")
np.add.accumulate(arr, axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-----------------


array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [267]:
arr = np.arange(3).repeat([1, 2, 2]) # 0-> once, 1 -> 2 times, 2 -> 2 times
print(arr.shape)
print(arr)
print("******")
print((np.arange(5).shape))
print(np.arange(5))
print("-------np.multiply.outer-------------")
print(np.multiply.outer(arr, np.arange(5)))
print("shape : ",np.multiply.outer(arr, np.arange(5)).shape)
print("-------np.multiply-------------")
print(np.multiply(arr, np.arange(5)))
print("--------arr * np.arange(5)-----------")
print(arr * np.arange(5))
print("--------np.dot------------")
np.dot(arr, np.arange(5))

(5,)
[0 1 1 2 2]
******
(5,)
[0 1 2 3 4]
-------np.multiply.outer-------------
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 2 4 6 8]
 [0 2 4 6 8]]
shape :  (5, 5)
-------np.multiply-------------
[0 1 2 6 8]
--------arr * np.arange(5)-----------
[0 1 2 6 8]
--------np.dot------------


17

In [268]:
x, y = np.random.randn(3, 4), np.random.randn(5)
print(x)
print(x.shape)
print("---------------")
print(y)
print(y.shape)
print("---------------")
result = np.subtract.outer(x, y)
print(result)
result.shape

[[ 0.5737  0.5605  0.2095 -0.8083]
 [ 0.8893  1.1924 -0.2881 -1.6406]
 [-1.6053 -1.2456 -1.0231  0.5297]]
(3, 4)
---------------
[ 0.7745 -1.7123  0.7562 -1.4077 -0.8812]
(5,)
---------------
[[[-0.2008  2.286  -0.1825  1.9814  1.4549]
  [-0.214   2.2728 -0.1957  1.9682  1.4417]
  [-0.565   1.9218 -0.5467  1.6172  1.0907]
  [-1.5828  0.9039 -1.5646  0.5993  0.0728]]

 [[ 0.1149  2.6016  0.1331  2.297   1.7705]
  [ 0.4179  2.9046  0.4361  2.6     2.0735]
  [-1.0626  1.4242 -1.0443  1.1196  0.5931]
  [-2.4151  0.0717 -2.3968 -0.2329 -0.7594]]

 [[-2.3798  0.107  -2.3615 -0.1976 -0.7241]
  [-2.0201  0.4667 -2.0018  0.1621 -0.3644]
  [-1.7976  0.6892 -1.7793  0.3846 -0.1419]
  [-0.2448  2.2419 -0.2266  1.9373  1.4108]]]


(3, 4, 5)

In [271]:
arr = np.arange(10)
print(arr)
np.add.reduce(arr)

[0 1 2 3 4 5 6 7 8 9]


45

In [272]:
arr = np.arange(10)
np.add.reduceat(arr, [0])

array([45])

In [274]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 2])

array([ 1, 44])

In [275]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 1])

array([ 0, 45])

In [276]:
arr = np.arange(10)
np.add.reduceat(arr, [2, 4])

array([ 5, 39])

In [277]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 4])

array([ 6, 39])

In [278]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5])

array([10, 35])

In [269]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

array([10, 18, 17])

In [ ]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr
np.add.reduceat(arr, [0, 2, 4], axis=1)

### Writing New ufuncs in Python

In [ ]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

In [ ]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

In [ ]:
arr = np.random.randn(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

## Structured and Record Arrays

In [ ]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

In [ ]:
sarr[0]
sarr[0]['y']

In [ ]:
sarr['x']

### Nested dtypes and Multidimensional Fields

In [ ]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

In [ ]:
arr[0]['x']

In [ ]:
arr['x']

In [ ]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']
data['y']
data['x']['a']

### Why Use Structured Arrays?

## More About Sorting

In [ ]:
arr = np.random.randn(6)
arr.sort()
arr

In [ ]:
arr = np.random.randn(3, 5)
arr
arr[:, 0].sort()  # Sort first column values in-place
arr

In [ ]:
arr = np.random.randn(5)
arr
np.sort(arr)
arr

In [ ]:
arr = np.random.randn(3, 5)
arr
arr.sort(axis=1)
arr

In [ ]:
arr[:, ::-1]

### Indirect Sorts: argsort and lexsort

In [ ]:
values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer
values[indexer]

In [ ]:
arr = np.random.randn(3, 5)
arr[0] = values
arr
arr[:, arr[0].argsort()]

In [ ]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter
zip(last_name[sorter], first_name[sorter])

### Alternative Sort Algorithms

In [ ]:
values = np.array(['2:first', '2:second', '1:first', '1:second',
                   '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer
values.take(indexer)

### Partially Sorting Arrays

In [ ]:
np.random.seed(12345)
arr = np.random.randn(20)
arr
np.partition(arr, 3)

In [ ]:
indices = np.argpartition(arr, 3)
indices
arr.take(indices)

### numpy.searchsorted: Finding Elements in a Sorted Array

In [ ]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(9)

In [ ]:
arr.searchsorted([0, 8, 11, 16])

In [ ]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])
arr.searchsorted([0, 1], side='right')

In [ ]:
data = np.floor(np.random.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

In [ ]:
labels = bins.searchsorted(data)
labels

In [ ]:
pd.Series(data).groupby(labels).mean()

## Writing Fast NumPy Functions with Numba

In [ ]:
import numpy as np

def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

```python
In [209]: x = np.random.randn(10000000)

In [210]: y = np.random.randn(10000000)

In [211]: %timeit mean_distance(x, y)
1 loop, best of 3: 2 s per loop

In [212]: %timeit (x - y).mean()
100 loops, best of 3: 14.7 ms per loop
```

```python
In [213]: import numba as nb

In [214]: numba_mean_distance = nb.jit(mean_distance)
```

```python
@nb.jit
def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count
```

```python
In [215]: %timeit numba_mean_distance(x, y)
100 loops, best of 3: 10.3 ms per loop
```

```python
from numba import float64, njit

@njit(float64(float64[:], float64[:]))
def mean_distance(x, y):
    return (x - y).mean()
```

### Creating Custom numpy.ufunc Objects with Numba

```python
from numba import vectorize

@vectorize
def nb_add(x, y):
    return x + y
```

```python
In [13]: x = np.arange(10)

In [14]: nb_add(x, x)
Out[14]: array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.])

In [15]: nb_add.accumulate(x, 0)
Out[15]: array([  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.])
```

## Advanced Array Input and Output

### Memory-Mapped Files

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+',
                 shape=(10000, 10000))
mmap

In [ ]:
section = mmap[:5]

In [ ]:
section[:] = np.random.randn(5, 10000)
mmap.flush()
mmap
del mmap

In [ ]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

In [ ]:
%xdel mmap
!rm mymmap

### HDF5 and Other Array Storage Options

## Performance Tips

### The Importance of Contiguous Memory

In [ ]:
arr_c = np.ones((1000, 1000), order='C')
arr_f = np.ones((1000, 1000), order='F')
arr_c.flags
arr_f.flags
arr_f.flags.f_contiguous

In [ ]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

In [ ]:
arr_f.copy('C').flags

In [ ]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

In [ ]:
%xdel arr_c
%xdel arr_f

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS