In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

In [2]:
>>> a = np.arange(9).reshape(3,3)
>>> b = np.arange(10,19).reshape(3,3)

In [3]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [39]:
ar1 = a[1,1:3]
ar1

array([4, 5])

In [40]:
br1 = b[1,1:3]
br1

array([14, 15])

In [42]:
#[4,5] concate [24, 15] along row
# np.concatenate((a[1,1:3],b[1,1:3]), axis=0)
np.concatenate((ar1,br1), axis=0)

array([ 4,  5, 14, 15])

* numpy.r_[array[ ], array[ ]] : 
concatenate any number of array slices along row (first) axis. 

In [20]:
np.r_[ ar1, br1] #row concatenate

array([ 4,  5, 14, 15])

In [43]:
ar2 = a[1,1:3].reshape(2,1)
ar2

array([[4],
       [5]])

In [44]:
br2 = b[1,1:3].reshape(2,1)
br2

array([[14],
       [15]])

In [45]:
np.r_[ ar2, br2] #row-wise concatenate. 

array([[ 4],
       [ 5],
       [14],
       [15]])

### numpy.c_[array[ ], array[ ]] : concatenate any number of array slices along column (second) axis.

In [32]:
a2  = a[0:2, 2].reshape(2,1)
a2

array([[2],
       [5]])

In [33]:
b2 = b[0:2, 2].reshape(2,1)
b2

array([[12],
       [15]])

In [34]:
np.c_[a2, b2]                   #column concatenate

array([[ 2, 12],
       [ 5, 15]])

In [36]:
a3 = a[0:2, 2]
a3

array([2, 5])

In [37]:
b3 = b[0:2, 2]
b3

array([12, 15])

In [38]:
np.c_[a3, b3] 

array([[ 2, 12],
       [ 5, 15]])